FROM project_name_docker_base_image

RUN bash

ENV DEBIAN_FRONTEND=noninteractive

# set the docker working dir to /project_name
WORKDIR /project_name

# ENTRYPOINT [ "conda activate project_name" ]
# CMD ["python","app.py"]